CREATE TABLE `wl_account` (
  `AccountID` varchar(64) NOT NULL COMMENT '帐号编号',
  `Account` varchar(100) NOT NULL COMMENT '帐号',
  `Password` varchar(512) NOT NULL COMMENT '密码',
  `HighPsaaword` varchar(512) DEFAULT NULL COMMENT '高级密码',
  `Email` varchar(100) DEFAULT NULL COMMENT '帐号关联电子邮件',
  `OldEmail` varchar(100) DEFAULT NULL COMMENT '帐号关联老电子邮件',
  `Mobile` varchar(64) DEFAULT NULL COMMENT '帐号关联手机号',
  `OldMobile` varchar(64) DEFAULT NULL COMMENT '帐号关联老手机号',
  `RegistTime` datetime DEFAULT sysdate() COMMENT '注册时间',
  `Status` int(11) NOT NULL DEFAULT 0 COMMENT '帐号状态（待注册验证，正常，安全异常，冻结，待再激活验证，销毁）',
  `TempPassword` varchar(512) DEFAULT NULL COMMENT '临时密码，验证码（短信，邮件）',
  `TempPassOverTime` datetime DEFAULT NULL COMMENT '临时密码，验证码过期时间',
  `TempPassUseFor` varchar(256) DEFAULT NULL COMMENT '临时密码用途标记',
  `TotalLoginTimes` bigint(20) DEFAULT 0 COMMENT '总登录次数',
  `LastLoginTime` datetime DEFAULT NULL COMMENT '最后登录时间',
  `ExtensionInfo` varchar(1000) DEFAULT NULL COMMENT '扩展信息',
  `Remark` varchar(500) DEFAULT NULL COMMENT '用户自己备注信息',
  `SysRemark` varchar(500) DEFAULT NULL COMMENT '系统备注信息',
  `UserID` varchar(64) NOT NULL COMMENT '用户id',
  `UserName` varchar(64) DEFAULT NULL COMMENT '用户名',
  `NickName` varchar(64) DEFAULT NULL COMMENT '用户昵称（通用昵称）',
  `LastNickName` varchar(64) DEFAULT NULL COMMENT '上个昵称',
  `NickPic` varchar(512) DEFAULT NULL COMMENT '昵称头像',
  `RealName` varchar(64) DEFAULT NULL COMMENT '真名',
  `RealFacePic` varchar(512) DEFAULT NULL COMMENT '真人头像',
  `IDCard` varchar(128) DEFAULT NULL COMMENT '身份证号码',
  `IDCardPic` varchar(10) DEFAULT NULL COMMENT '身份证明照片',
  `Address` varchar(200) DEFAULT NULL COMMENT '地址信息',
  `MainPic` varchar(512) DEFAULT NULL COMMENT '主图片',
  `CoreID` varchar(64) NOT NULL COMMENT '核心ID',
  `IsDel` int(11) NOT NULL DEFAULT 0 COMMENT '是否删除：0未删除，1删除',
  `Disabled` int(11) NOT NULL DEFAULT 0 COMMENT '是否不可用：0可用，1不可用',
  `IsRecycle` int(11) NOT NULL DEFAULT 0 COMMENT '是否回收：0不回收，1回收',
  `CreatorID` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `Creator` varchar(64) DEFAULT NULL COMMENT '创建人',
  `CreateTime` datetime DEFAULT current_timestamp() COMMENT '创建时间',
  `EditorID` varchar(64) DEFAULT NULL COMMENT '最后修改人ID',
  `Editor` varchar(64) DEFAULT NULL COMMENT '最后修改人',
  `EditTime` datetime DEFAULT current_timestamp() COMMENT '最后修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
